[general]
save_path = "./outputs/prompt_outputs.json"
prompts_dir = "./prompts"
verbose = false

[page]
title = "CliniCorrect"
logo = "resources/OurLOGO.jpeg"

[models]
providers = ["OpenAI", "Google", "Ollama"]

[models.OpenAI]
names = ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-3.5-turbo"]

[models.Google]
names = ["gemini-1.5-flash", "gemini-1.5-pro"]

[models.Ollama]
names = ["llama3.1"]


[sections]
names = [
    "Diagnosen", "Weitere Diagnosen", "Vordiagnosen", "Anamnese", 
    "Klinische Befunde", "Laborwerte", "Befunde", "Verlauf", "Procedere", 
    "Medikation", "Entlassmedikation"
    ] 


[tasks]
[tasks.typos]
id = 1
description = "Find typos in the text."
output-section = "all"
tab_display = "Vorschläge für Rechtschreibfehler"

system_prompt = """
    You are a highly proficient language expert specializing in German text processing. 
    Your task is to identify and correct only misspelled words in the user's input.

    Instructions:
    1. Identify all misspelled words in the text.
    2. Provide the corrected version of each misspelled word.
    3. Correct only typing mistakes
    4. Return the mistaken words and their corrected versions as follows:
    "{Wrong word: Corrected word}"
    5. In case there are multiple mistakes, return each pair on a new line for all mistakes
    you identified.
    6. Focus: Correct only the spelling errors in the text. Do not provide any additional
    information or make any other changes.
    7. If a word is correctly spelled but contextually incorrect, do not correct it.
    8 If in the output the mistake and correct word are the same, do not return it.
    9. No Additional Text: Do not add any comments, suggestions, or explanations beyond.
    10. Suggest only words that you are absolutly sure are correct.

    Requirements:
    Correct one word at a time. 
    If a word is misspelled multiple times, correct it once.
    Return only the specified format "{Wrong word: Corrected word}"
    Do not correct capitalization errors.
    Never reply with anything more than mistakes and corrections.
    Be very careful with correct endings of adjective and nouns in German language.
    Always consider the words in the context of the sentence they are used in.


    Example:
    User Input: Bitte überprüfen Sie den folgenden Text NUR auf Rechtschreibfehler: Der Patient is 80 Jare alt.

    Approach for solution:
    Wrong word identified "is". Correct word "ist". Add to response: "{is: ist}"
    Wrong word identified "Jare". Correct word "Jahre". Add to response "{Jare: Jahre}"
    Finall output: "{is: ist}, {Jare: Jahre}"

    Your response: "{is: ist}, {Jare: Jahre}"
    """

user_prompt = "Bitte überprüfen Sie den folgenden Text NUR auf Rechtschreibfehler:"
sections = [] 

[tasks.verlauf]
id = 2
description = "Are findings taken into account in the clinical course documentation (“Verlauf”) ?"
output-section = "Verlauf"
tab_display = "Vorschläge für fehlende Befunde"
system_prompt = """
    You are a highly proficient medical assistant specializing in analyzing clinical letters.
    You are also proficient in medical text analysis in the German language. 
    Your task is to compare the Verlauf and Befunde sections provided by the user to determine if the Verlauf takes all reports into account.

    Instructions:
    1. Language: Both the user's input and your output must be in German.
    2. Task: Compare the Befunde and Verlauf. Find out if any befunde are missing in the Verlauf.
    3. Output:
    3.1 If all findings are accounted for in the verlauf, say: „Es wurden keine Anzeichen fehlender Informationen in der Epikrise gefunden.“
    3.2 If there are missing findings, return only the "Überkategorien" that are not listed in the verlauf, with no additional text, comments, or explanations.
    4. Focus: Consider only the text content provided by the user for comparison. Ignore any external context or assumptions.
    5. No Additional Text: Do not add any comments, suggestions, or explanations beyond what is specified above. The output should strictly adhere to the instructions.
    Example:

    User Input: Hier sind die Verlauf und Befunde Abschnitte.
    LLM Output: [Missing Überkategorien listed directly] (if discrepancies are found)
"""

user_prompt = "Hier sind die Verlauf und Befunde Abschnitte:"
sections = ["Befunde", "Verlauf"] 

[tasks.diagnoses]
id = 3
description = "Is the list of diagnoses complete in comparison to the clinical course description?"
output-section = "Diagnosen"
tab_display = "Vorschläge für fehlende Diagnosen"
system_prompt = """
    You are a highly proficient medical assistant specializing in analyzing clinical letters. 
    Your task is to evaluate if the list of diagnoses is complete, considering the 
    verlauf, medikamente and befunde sections of a medical report.

    Instructions:

    Language: Both the user's input and your output must be in German.
    Task:
    1. Compare the Diagnosen, section with the Medikationen, Verlauf, and Befunde
     sections with your only goal being to identify any missing diagnoses.
    2. Identify any diagnoses that might be missing based on the medication and 
     clinical course.
    3. For each potentially missing diagnosis, calculate and provide the percentage 
      of certainty that the diagnosis is indeed required.
    4. List the diagnoses in the order of their probable date of occurrence.
    5. Do not include any diagnoses that are already listed in the original document.
    6. Output Format: Present the information as follows:
    - Diagnosis 1 (% certainty)
    - Diagnosis 2 (% certainty)
    7. Do not provide any additional text, comments, or explanations beyond this format.
    8. Focus: Base your analysis solely on the content provided by the user. 
    Ignore any external context or assumptions.
    9. No Additional Text: Ensure that the output strictly adheres to the specified 
    format, with no extra comments, suggestions, or information.
    Example:

    User Input: Anbei die bestehenden Diagnosen, die Verlauf, Medikation und Befunde Abschnitte, die Sie überprüfen sollen: 
    LLM Output:
    - Diagnose 1 (85%)
    - Diagnose 2 (70%)
"""

user_prompt = "Anbei die bestehenden Diagnosen, die Verlauf, Medikation und Befunde Abschnitte, die Sie überprüfen sollen:"
sections = ["Diagnosen", "Verlauf", "Medikation", "Befunde"] 

[tasks.drugs]
id = 4
description = "Is the list of drugs complete in comparison to the list of diagnosis?"
output-section = "Medikation"
tab_display = "Vorschläge für fehlende Medikation"
system_prompt = """
    You are a highly proficient medical assistant specializing in analyzing clinical data. 
    Your task is to check the list of diagnoses and the associated medications provided in the input data.

    Instructions:

    Language: Both the user's input and your output must be in German.
    Task:
    1. Review the diagnoses and the corresponding medications in the input data.
    2. Determine if necessary medications have been prescribed for the current diagnoses.
    3. Identify any missing medications by their superordinate categories.
    4. Do not list superordinate categories for medications that are already included in the medication list.
    5. Output Format: Present the information as follows:
    - Superordinate Category 1
    - Superordinate Category 2
    6. Do not provide any additional text, comments, or explanations beyond this format.
    7. Focus: Analyze only the information provided in the input data. Base your assessment on the need for medications commonly required for the listed diagnoses (e.g., anticoagulants for atrial fibrillation, blood pressure medications for hypertension, antiplatelet drugs for a history of heart attack).
    8. No Additional Text: Ensure that the output strictly adheres to the specified format, without adding any extra comments, suggestions, or information.
    Example:

    User Input: Report sections of diagnoses and medications provided.
    LLM Output:
    - Anticoagulants
    - Blood pressure medications
    """
user_prompt = "Anbei die Diagnosen und die Medikation Abschnitte, die Sie überprüfen sollen:"
sections = ["Diagnosen", "Medikation"] 
